### ISSUE TITLE
Prep and Publish v0.0.1

### ISSUE THREAD

**Issue by Ethan-Arrowood** [Ethan-Arrowood/compile-schemas-to-typescript#2]
Couple things necessary before we publish the initial version of this module.

- [x] Set up CI (either using Azure Pipelines or GitHub actions)
- [x] Add error cases + tests
    - i.e. invalid functions arguments
    - i.e. directory already exists
- [x] figure out build->deploy process 
    - module is written in TypeScript so when we publish we need to publish the `build` directory output rather than the `src` directory.

**Comment by Ethan-Arrowood** [comment]
@fastify/fastify can someone help me with setting up CI for this repo-or just point me in the right direction? I know we've been using GitHub Actions instead of Azure Pipelines. Happy to use Actions just need to know where to start setting it up for this repo 😁

@fastify/leads what is the process of getting this module published on npm? Everything should be good to go in the package.json (prepublish command, main code path, and types path). I think I have the ability to publish to certain fastify modules on npm but not sure what to do for an initial release.

And last note: if someone has a better idea for the name of this module let me know. Welcoming other ideas before we do the initial publish!

**Comment by mcollina** [comment]
## CI config

Just configure github actions and you should be good to go. There is no admin task needed to do that, you should be able to add the config file here and they should kick in.

## Publishing on npm

publish on npm and then add me or @delvedor, we'll add it to the org.

## Naming

I think this module name is just fine. I'm really bad at names and this does what it says.

## Versioning

I would release v0.1.0.

**Comment by Ethan-Arrowood** [comment]
v0.1.0 has been released
